import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {ArrowDownToLine, ArrowUpRight, Award, BarChart3, BriefcaseBusiness, Building2, Check, ChevronRight, Code2, Database, ExternalLink, FileText, Github, GraduationCap, LayoutDashboard, Linkedin, LockKeyhole, Mail, Menu, Play, Search, Send, ShieldCheck, Sparkles, X} from 'lucide-react';
import './styles.css';

const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=url&&key?createClient(url,key):null;
const fallback={
 profile:{name:'Abhishek Jatav',role:'Data Analyst',headline:'Turning Data into Insights & Decisions',email:'abhijadav01212@gmail.com',location:'Indore, Madhya Pradesh, India',photo_url:'/abhishek.jpg',about:'I am a B.Tech Information Technology graduate and aspiring Data Analyst. I enjoy turning untidy, raw data into clear stories, useful dashboards, and business-focused decisions.'},
 organizations:['Unified Mentor Pvt. Ltd.','IBM','Packt','Maven Analytics','Microsoft','Tableau','Google','Coursera','Amazon Web Services'].map((name,i)=>({id:'o'+i,name,logo_url:'/icons/'+['unified','ibm','packt','maven','microsoft','tableau','google','coursera','aws'][i]+'.png',display_order:i})),
 skills:[['Excel','Advanced'],['SQL','Intermediate'],['Power BI','Intermediate'],['Python','Intermediate'],['Tableau','Beginner'],['Data Analysis','Advanced'],['Data Visualization','Advanced']].map(([name,level],i)=>({id:'s'+i,name,icon_url:'/icons/'+['excel','sql','powerbi','python','skill-tableau','analysis','visualization'][i]+'.png',level,display_order:i})),
 projects:[
 {id:'p1',title:'Employee Attrition Prediction & Risk Scoring',category:'Machine Learning',stack:['Python','Pandas','Scikit-learn','Streamlit'],description:'An interactive app for employee-level attrition analysis and risk scoring.',problem:'Help teams identify retention risk early.',insights:'Combines predictive risk scores with readable business analysis.',github_url:'https://github.com/abhijadav01212-dot/Employee-Attrition-Prediction-System-2026',live_url:'https://employee-attrition-prediction-system-sh1j.onrender.com/'},
 {id:'p2',title:'European Banking Customer Segmentation',category:'Data Visualization',stack:['Python','SQL','Power BI','Streamlit'],description:'Customer behavior, segmentation and churn analytics for better retention decisions.',problem:'Make customer patterns useful to business teams.',insights:'Interactive views support segmentation and churn exploration.',github_url:'https://github.com/abhijadav01212-dot/European-Bank-Customer-Segmentation-Churn-Analytics',live_url:'https://european-bank-dashboard.streamlit.app'},
 {id:'p3',title:'Care Transition Efficiency Analytics',category:'Data Analytics',stack:['Python','Pandas','Power BI'],description:'KPI dashboard for care-transition efficiency and placement outcomes.',problem:'Give operations teams a clear monitoring view.',insights:'Focuses attention on placement and efficiency indicators.',github_url:'https://github.com/abhijadav01212-dot/Care-Transition-Analytics',live_url:'https://care-transition-analytics01.streamlit.app'},
 {id:'p4',title:'Super Store Sales Dashboard',category:'Excel',stack:['Advanced Excel','Pivot Tables','Slicers'],description:'Interactive sales dashboard built with dynamic reports and KPI visuals.',problem:'Transform sales rows into timely performance insights.',insights:'Pivot-driven reporting makes drilldowns practical.',github_url:'https://github.com/abhijadav01212-dot/super-store-sales-dashboard-excel'}
 ],
 certificates:[['Unified Mentor Pvt. Ltd.','Data Analytics Fellowship',null,'unified'],['IBM','Introduction to Data Analytics','https://www.coursera.org/account/accomplishments/verify/BFBEYPC4GCH1','ibm'],['Packt','Master SQL for Data Analysis','https://www.coursera.org/account/accomplishments/verify/X2MDWMHELCUG','packt'],['Maven Analytics','ChatGPT & Generative AI for Data Analytics','https://www.coursera.org/account/accomplishments/verify/DK5CZOZLYIBK','maven'],['Microsoft','Harnessing the Power of Data with Power BI','https://www.coursera.org/account/accomplishments/verify/ZCYJX5V035ZT','microsoft'],['Tableau','Data Analysis with Tableau','https://www.coursera.org/account/accomplishments/verify/T014GK0HAKYG','tableau'],['Google','Hello, Python!','https://www.coursera.org/account/accomplishments/verify/EKXVKB3HS4EH','google'],['Coursera','AWS S3 Basics','https://www.coursera.org/account/accomplishments/verify/APXUDZ631QAU','coursera']].map(([organization,title,certificate_url,logo],i)=>({id:'c'+i,organization,title,certificate_url,logo_url:'/icons/'+logo+'.png',issue_date:'2026',display_order:i})),
 offers:[{id:'l1',company:'Saiket Systems',position:'Data Visualization Intern',type:'Internship',image_url:'/saiket-offer.jpg'},{id:'l2',company:'Cognifyz IT Solutions',position:'Data Visualization Intern',type:'Internship',image_url:'/cognifyz-offer.jpg'},{id:'l3',company:'Unified Mentor Pvt. Ltd.',position:'Data Analyst Intern',type:'6-month internship',image_url:'/unified-offer.jpg'}]
};
const Icon=({name,size=23})=>{const map={Excel:FileText,SQL:Database,'Power BI':BarChart3,Python:Code2,Tableau:BarChart3,'Data Analysis':Search,'Data Visualization':BarChart3};const C=map[name]||Sparkles;return <C size={size}/>};
function App(){const [data,setData]=useState(fallback),[menu,setMenu]=useState(false),[modal,setModal]=useState(null),[admin,setAdmin]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{if(!supabase)return; Promise.all(['profile','organizations','skills','projects','certificates','offer_letters'].map(t=>supabase.from(t).select('*').eq('status','published').order('display_order'))).then(res=>{if(res.every(x=>!x.error)){const [profile,organizations,skills,projects,certificates,offers]=res.map(x=>x.data);setData(d=>({...d,profile:profile[0]||d.profile,organizations:organizations||d.organizations,skills:skills||d.skills,projects:projects||d.projects,certificates:certificates||d.certificates,offers:offers||d.offers}))}})},[]);
 const filtered=data.projects.filter(p=>(p.title+p.category+p.stack.join(' ')).toLowerCase().includes(query.toLowerCase()));
 return <><header><a className="brand" href="#home">ABHISHEK <span>JATAV</span><Send size={18}/></a><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}>{['Home','About','Skills','Projects','Certificates','Resume','Achievements','Offer Letters','Contact'].map(x=><a onClick={()=>setMenu(false)} href={'#'+x.toLowerCase().replace(' ','-')} key={x}>{x}</a>)}</nav><div className="actions"><button className="ghost" onClick={()=>setModal({type:'resume'})}>View Resume <ArrowDownToLine/></button><a className="primary" href="#contact">Get In Touch <Send/></a></div></header>
 <main><section id="home" className="hero"><div className="hero-copy"><p className="eyebrow"><i/> DATA ANALYTICS & VISUALIZATION ENTHUSIAST</p><h1>Hi, I’m <span>Abhishek Jatav</span></h1><h2>{data.profile.headline}</h2><p className="lede">Aspiring Data Analyst skilled in Excel, SQL, Power BI, Python and Data Visualization. I transform raw data into meaningful insights, interactive dashboards and business-focused solutions.</p><div className="cta"><a className="primary" href="#projects">View My Work <ArrowUpRight/></a><button className="ghost" onClick={()=>setModal({type:'resume'})}>Download Resume <ArrowDownToLine/></button></div></div><div className="portrait-wrap"><div className="portrait-bg"/><img className="portrait" src={data.profile.photo_url||'/abhishek.jpg'} alt="Abhishek Jatav"/><SkillFloat cls="one" icon={<BarChart3/>} title="Data Analysis" text="Excel · SQL · Python"/><SkillFloat cls="two" icon={<BarChart3/>} title="Data Visualization" text="Power BI · Tableau"/><SkillFloat cls="three" icon={<Sparkles/>} title="Business Insights" text="Transforming Data"/><SkillFloat cls="four" icon={<ShieldCheck/>} title="Problem Solver" text="Analytical Thinking"/></div></section>
 <section className="strip" aria-label="Organizations">{data.organizations.map(o=><div className="org" key={o.id}>{o.logo_url?<img src={o.logo_url} alt=""/>:<Building2/>}<b>{o.name}</b></div>)}</section>
 <Section id="skills" eyebrow="CAPABILITIES" title="My Tech Skills"><div className="skill-grid">{data.skills.map(s=><article className="skill-card" key={s.id}>{s.icon_url?<img src={s.icon_url} alt=""/>:<Icon name={s.name}/>}<h3>{s.name}</h3><p>{s.level}</p><div><i style={{width:s.level==='Advanced'?'88%':s.level==='Intermediate'?'67%':'42%'}}/></div></article>)}</div></Section>
 <Section id="projects" eyebrow="SELECTED WORK" title="Projects"><div className="tool-row"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects"/></div>{['All','Data Analytics','Excel','Power BI','Python','SQL','Tableau'].map(x=><button key={x} onClick={()=>setQuery(x==='All'?'':x)}>{x}</button>)}</div><div className="project-grid">{filtered.map(p=><article className="project-card" key={p.id}><div className="project-art"><BarChart3 size={50}/><span>{p.category}</span></div><div className="card-body"><p className="label">{p.category}</p><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.stack.map(x=><small key={x}>{x}</small>)}</div><div className="project-links"><a href={p.github_url} target="_blank" rel="noreferrer"><Github/> GitHub</a>{p.live_url&&<a href={p.live_url} target="_blank" rel="noreferrer">Open Project <ArrowUpRight/></a>}</div></div></article>)}</div></Section>
 <Section id="certificates" eyebrow="CREDENTIALS" title="Certificates"><div className="certificate-grid">{data.certificates.map(c=><article key={c.id} className="certificate">{c.logo_url?<img src={c.logo_url} alt=""/>:<Award/>}<div><p>{c.organization}</p><h3>{c.title}</h3><small>Issued {c.issue_date||'2026'}</small></div>{c.certificate_url?<a href={c.certificate_url} target="_blank" rel="noreferrer">View <ArrowUpRight/></a>:<button onClick={()=>setModal({type:'certificate',item:c})}>View <ArrowUpRight/></button>}</article>)}</div></Section>
 <Section id="resume" eyebrow="PROFESSIONAL PROFILE" title="My Resume"><div className="resume-card"><FileText/><div><h3>Data Analyst Resume</h3><p>Skills, projects, experience and education in one document.</p><small>Last updated: August 2026</small></div><button className="primary" onClick={()=>setModal({type:'resume'})}>View Resume <ArrowUpRight/></button></div></Section>
 <Section id="offer-letters" eyebrow="EXPERIENCE" title="Offer Letters"><div className="offer-grid">{data.offers.map(o=><article className="offer" key={o.id}><img src={o.image_url} alt={`${o.company} offer letter`} loading="lazy"/><div><p>{o.type}</p><h3>{o.company}</h3><span>{o.position}</span><button onClick={()=>setModal({type:'offer',item:o})}>View Offer Letter <ArrowUpRight/></button></div></article>)}</div></Section>
 <Section id="about" eyebrow="ABOUT ME" title="Building clarity from complexity"><div className="about"><img src={data.profile.photo_url||'/abhishek.jpg'} alt="Abhishek Jatav"/><div><p>{data.profile.about}</p><p>My focus is data cleaning, exploratory analysis, KPI dashboard development, and translating analytical work into decisions that teams can act on.</p><div className="stats"><span><b>Excel</b> Advanced analysis</span><span><b>BI</b> Power BI & Tableau</span><span><b>Python</b> Data workflows</span></div></div></div></Section>
 <Section id="achievements" eyebrow="MILESTONES" title="Achievements"><div className="achievement"><GraduationCap/><div><h3>Data Analytics Fellowship</h3><p>Unified Mentor Pvt. Ltd. · Jul 2026 – Present</p><span>Hands-on analytics work across customer, healthcare, banking and employee use cases.</span></div></div></Section>
 <section id="contact" className="contact"><div><p className="eyebrow"><i/> LET’S CONNECT</p><h2>Have a data story to tell?</h2><p>Let’s discuss dashboards, analytical projects, and opportunities.</p><a href={`mailto:${data.profile.email}`}><Mail/> {data.profile.email}</a><p><Building2/> {data.profile.location}</p></div><form onSubmit={e=>{e.preventDefault();alert('Thank you — your message is ready to send. Connect Supabase to receive contact messages.')}}><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/><input required placeholder="Subject"/><textarea required placeholder="Message" rows="4"/><button className="primary">Send Message <Send/></button></form></section></main>
 <footer><div className="brand">ABHISHEK <span>JATAV</span></div><p>Data Analyst | Data Visualization</p><div><a href="https://linkedin.com" aria-label="LinkedIn"><Linkedin/></a><a href="https://github.com" aria-label="GitHub"><Github/></a><a href={`mailto:${data.profile.email}`} aria-label="Email"><Mail/></a><button className="admin-link" onClick={()=>setAdmin(true)} aria-label="Admin access"><LockKeyhole size={15}/></button></div><small>© 2026 Abhishek Jatav. All Rights Reserved.</small></footer>
 {modal&&<Viewer modal={modal} close={()=>setModal(null)}/>} {admin&&<Admin close={()=>setAdmin(false)} data={data} setData={setData}/>}</>}
const SkillFloat=({cls,icon,title,text})=><div className={'float '+cls}><span>{icon}</span><div><b>{title}</b><small>{text}</small></div></div>;
const Section=({id,eyebrow,title,children})=><section id={id} className="section"><p className="section-eye">{eyebrow}</p><h2>{title}</h2>{children}</section>;
function Viewer({modal,close}){let body;if(modal.type==='resume')body=<iframe title="Resume viewer" src="/resume.pdf#view=FitH"/>;else if(modal.type==='offer')body=<img src={modal.item.image_url} alt="Offer letter preview"/>;else if(modal.type==='project')body=<div className="case"><p className="label">{modal.item.category}</p><h2>{modal.item.title}</h2><h3>Business problem</h3><p>{modal.item.problem}</p><h3>Key outcome</h3><p>{modal.item.insights}</p><div className="tags">{modal.item.stack.map(x=><small key={x}>{x}</small>)}</div></div>;else body=<div className="case"><Award size={46}/><h2>{modal.item.title}</h2><p>{modal.item.organization}</p><p>Credential detail will display the uploaded PDF or certificate image once configured in the admin dashboard.</p></div>;return <div className="modal" role="dialog"><button className="close" onClick={close}><X/></button><div className="viewer">{body}</div></div>}
function Admin({close,data,setData}){const [ok,setOk]=useState(false),[section,setSection]=useState('Skills'),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const groups={Skills:'skills',Organizations:'organizations',Projects:'projects',Certificates:'certificates','Offer Letters':'offers'};const table=groups[section];const verify=async e=>{e.preventDefault();setBusy(true);setError('');let authorized=false;if(supabase){const {data:r,error:callError}=await supabase.functions.invoke('verify-admin-code',{body:{code}});authorized=!callError&&r?.authorized}else{try{const r=await fetch('/api/verify-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});authorized=(await r.json()).authorized}catch{setError('Local admin service is unavailable. Restart the development server.')}}setOk(authorized);if(!authorized&&!error)setError('Incorrect access code. Please try again.');setBusy(false)}; if(!ok)return <div className="modal admin"><button className="close" onClick={close}><X/></button><form className="login" onSubmit={verify}><LockKeyhole/><h2>Admin Dashboard</h2><p>Enter your private access code.</p><input autoFocus type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Access code"/><button className="primary" disabled={busy}>{busy?'Checking…':'Continue'}</button>{error&&<small className="login-error">{error}</small>}{!supabase&&<small>Local development mode is active. Connect Supabase for persistent public updates.</small>}</form></div>;return <div className="modal admin"><div className="dash"><aside><b><LayoutDashboard/> Portfolio CMS</b>{['Dashboard','Profile','About','Skills','Organizations','Projects','Certificates','Resume','Offer Letters','Achievements','Contact Messages','Settings'].map(x=><button className={x===section?'active':''} onClick={()=>setSection(x)} key={x}>{x}</button>)}<button onClick={close}>Exit dashboard</button></aside><div className="manage"><h2>{section}</h2><p>Connected content can be added, edited, reordered or removed here.</p>{table?<ContentEditor table={table} rows={data[table]} setData={setData}/>:<div className="empty"><ShieldCheck/><h3>{section} management</h3><p>Use Supabase tables and storage from the included setup to manage this section securely.</p></div>}</div></div></div>}
function ContentEditor({table,rows,setData}){const [draft,setDraft]=useState('');const add=async()=>{if(!draft.trim())return;const item={id:crypto.randomUUID(),name:draft,title:draft,company:draft,organization:'Independent',level:'Intermediate',display_order:rows.length};if(supabase){const dbTable=table==='offers'?'offer_letters':table;const {data:r,error}=await supabase.from(dbTable).insert(item).select().single();if(error)return alert(error.message);item.id=r.id}setData(d=>({...d,[table]:[...d[table],item]}));setDraft('')};return <><div className="add-row"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={`Add ${table.slice(0,-1)}`}/><button className="primary" onClick={add}>Add</button></div><div className="admin-list">{rows.map((x,i)=><div key={x.id}><span>{i+1}</span><b>{x.name||x.title||x.company}</b><button onClick={()=>setData(d=>({...d,[table]:d[table].filter(y=>y.id!==x.id)}))}>Delete</button></div>)}</div></>}
createRoot(document.getElementById('root')).render(<App/>);
